
name: Deploy main
on:
  workflow_dispatch:
  push:
    paths:
      - 'profile/README.md'


jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    needs: tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install

      - name: Run scrapy
        env:
          TOKEN: ${{ secrets.GIT_USER_PAT }}
          OWNER: ${{ github.repository_owner }}
        run: npm run start

      - name: Render markdown
        run: |
          echo "### Markdown" >> $GITHUB_STEP_SUMMARY
          cat profile/README.md >> $GITHUB_STEP_SUMMARY

      - name: Configure git
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_USER_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Detect changes
        id: changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git checkout main
          git commit -m "chore(update): update readme" --author="zork-bork <${{ secrets.GIT_USER }}>" --signoff
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_USER_PAT }}
