name: Deploy main

on:
  workflow_dispatch:
  push:
    paths:
      - 'profile/README.md'

permissions:
  actions: 'write'
  checks: 'write'
  contents: 'write'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'
  statuses: 'write'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm install
    - run: npm run start

    - name: Render markdown
      run: |
        echo "### Markdown" >> $GITHUB_STEP_SUMMARY
        cat profile/README.md >> $GITHUB_STEP_SUMMARY
    - name: "Import GPG key"
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: "Commit and push changes"
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
        commit_user_name: ${{ steps.import-gpg.outputs.name }}
        commit_user_email: ${{ steps.import-gpg.outputs.email }}
        commit_message: "chore(update): Update README.md"