name: Deploy main

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

permissions:
  actions: 'write'
  checks: 'write'
  contents: 'write'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'
  statuses: 'write'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm install
    - run: npm run start

    - name: Render markdown
      run: |
        echo "### Markdown" >> $GITHUB_STEP_SUMMARY
        cat profile/README.md >> $GITHUB_STEP_SUMMARY

    - name: Commit and Push Changes
      run: |
        if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "chore(update): Update readme"
            git push
          fi
        fi
