name: Deploy main

on:
  workflow_dispatch:
  push:
    paths:
      - 'profile/README.md'

permissions:
  actions: 'write'
  checks: 'write'
  contents: 'write'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'
  statuses: 'write'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    needs: tests
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Use Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm install
    - run: npm run start

    - name: Render markdown
      run: |
        echo "### Markdown" >> $GITHUB_STEP_SUMMARY
        cat profile/README.md >> $GITHUB_STEP_SUMMARY

    - name: Configure git
      run: |
        git config --global user.name "${{ secrets.GIT_USER }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - name: Commit changes
      run: |
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "chore(update): update readme" --author="Zorg <${{ secrets.GIT_EMAIL }}>" --signoff
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_USER_PAT }}