name: Release

on:
  workflow_run:
    workflows: ["production"]
    types:
      - 'completed'

permissions:
  actions: 'write'
  checks: 'write'
  contents: 'write'
  id-token: 'write'
  issues: 'write'
  pull-requests: 'write'
  statuses: 'write'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release:
    needs: [ tests ]
    if: ${{ always() && github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/semantic-release.yml